# Generated by Django 4.1.6 on 2023-03-19 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0003_userprofile_tagfollow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followed_tags',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='TagFollow',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
