# Generated by Django 4.1.6 on 2023-03-19 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
