# Generated by Django 4.1.6 on 2023-04-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0009_photo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(default='nothing', max_length=200),
        ),
    ]
