# Generated by Django 4.1.6 on 2023-04-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0012_remove_photo_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
